### ISSUE TITLE
2023/2/20 To-Do List

### ISSUE THREAD

**Issue by yilinxia** [VMarkos/prudens-viz-temp#6]
Small Issues
- [x] Fix Policy Section  ( if nothing input in this policy, the graph and console part will update accordingly)
- [x] Get rid of the redundant files for the Github repo

Major Issues
**Layout Algorithm** 
- [ ] Cross edges https://www.csd.uoc.gr/~hy583/papers/ch10.pdf 
- [ ] Layout Algorithm

**Comment by VMarkos** [comment]
I completed the first two tasks, i.e., output/graph upload in case of empty policies and repo cleanup (I will push any changes once we are done with our meeting today).
